services:
  emo:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: emo
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
      - PYTHONUNBUFFERED=1
      - PORT=5000
    ports:
      - 5001:5000

    volumes:
      - ./Configuration.txt:/app/src/Configuration.txt
      - ./Results.txt:/app/Results.txt
      # - emo-data:/app
# volumes:
# emo-data:
